let
    // Define the language.
    // Options: en-US (default),  pt-BR, es-ES, hi-IN, fr-FR, de-DE
    Culture = "en-US",
    PeriodsNamesInput = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("VY89EgIhDIXvQr0cAmfXTgt/qp0t4pIFCsIOwnggLWw9AxeTsDZWecl8eXkZR4Ekr2fRiR4eVMshRHJkqlJLwkgh8PTojE1i6kaxJrk7MQc6ZgMamiZbnlVcIGpkPLiEDce7HNhdeSCcMTa6fIDgD5/thi9R7tld5Rs2NDk+r9ZY3nfpnXaMZ7dl0Sj7gaOXl/cYc4tdHzDYMsNsvUsJzK+pS9MX", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Culture = _t, Dawn = _t, Morning = _t, Afternoon = _t, Night = _t]),
    PeriodsTb = Table.RemoveColumns ( Table.SelectRows ( PeriodsNamesInput, each [Culture] = Culture ), "Culture" ),
    ColumnNamesTbInput = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZFNTsMwEIWvYnndSBUb9k2KQAipamDTkIUbTxtLsadybCjcgUOwgiy4ATtfDMf57Y7VzDx73mc9ZxkFFT2ldEHvFIezr49CArmHN9+mhmlD8EAehLIG5sotWu3nvkznUKDivtmAFshpvsjoyUSrrZfch+KigLCl3ac/J3HJXlohRgnuCwlHIlsrnGuMlKhZt8YGGAbY0SqOHc39oG9bHtTROr3gxZXHEA7ECJCn3lyAevfuUF0gJ3W8+0/sQUc32y7Hgeqa2tfENXtrWrwcYpqk6tkul1fXJVgdkunrGGgC9izct2z7jWvaUCHgOETJevZtOxCmLsrK/dY1VKMF2cNRKAUqfJ5/N5BVUMZ5Ttu9ehfo3TSzkub5Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Culture = _t, Index = _t, #"Time Key" = _t, #"Start of Minute" = _t, #"Start of Hour" = _t, Hour = _t, Minute = _t, Second = _t, Period = _t]),
    ColumnNamesTb = Table.RemoveColumns (
        Table.SelectRows ( ColumnNamesTbInput, each [Culture] = Culture ),
        "Culture"
    ),
    DawnName = PeriodsTb[Dawn]{0},
    MorningName = PeriodsTb[Morning]{0},
    AfternoomName = PeriodsTb[Afternoon]{0},
    NightName = PeriodsTb[Night]{0},
    ZeroWidthSpace = Character.FromNumber ( 8203 ),
    AddIndex = Table.FromList ( 
        {0..86399}, 
        Splitter.SplitByNothing(), 
        type table [ Index = Int64.Type ] 
    ),
    AddTimeKey = Table.AddColumn ( 
        AddIndex, 
        "Time Key", 
        each 
            let 
                duration = #duration ( 0, 0, 0, [Index] ),
                hours = Duration.Hours ( duration ),
                minutes =Duration.Minutes ( duration ),
                seconds = Duration.Seconds ( duration ) in
                #time ( hours, minutes, seconds ),
        type time
    ),
    AddStartOfMinute = Table.AddColumn ( 
        AddTimeKey, 
        "Start of Minute", 
        each #time ( Time.Hour ( [Time Key ] ), Time.Minute ( [Time Key] ) , 0 ), 
        type time 
    ),
    AddStartOfHour = Table.AddColumn ( 
        AddStartOfMinute, 
        "Start of Hour", 
        each Time.StartOfHour ( [Time Key] ), 
        type time 
    ),
    AddHour = Table.AddColumn ( 
        AddStartOfHour, 
        "Hour", 
        each Time.Hour ( [Time Key] ), 
        Int64.Type 
    ),
    AddMinute = Table.AddColumn ( 
        AddHour, 
        "Minute", 
        each Time.Minute ( [Time Key] ),  
        Int64.Type 
    ),
    AddSecond = Table.AddColumn ( 
        AddMinute, 
        "Second", 
        each Time.Second ( [Time Key] ), 
        Int64.Type 
    ),
    AddPeriod = Table.AddColumn ( 
        AddSecond, 
        "Period", 
        each if [Hour] < 6 then Text.Repeat(ZeroWidthSpace,4) & DawnName 
            else if [Hour] < 12 then Text.Repeat(ZeroWidthSpace,3) & MorningName 
            else if [Hour] < 18 then Text.Repeat(ZeroWidthSpace,2) & AfternoomName 
            else ZeroWidthSpace & NightName, 
        type text 
    ),
    ReorderedColumns = Table.ReorderColumns(
        AddPeriod,
        {
            "Index", 
            "Time Key", 
            "Start of Minute", 
            "Start of Hour", 
            "Hour", 
            "Minute", 
            "Second", 
            "Period"
        }
    ),
    ListToRename = Table.AddColumn (
        Table.UnpivotOtherColumns ( ColumnNamesTb, {}, "From", "To" ),
        "FromTo",
        each Record.FieldValues ( _ )
    )[FromTo],
    RenamedColumns = Table.RenameColumns ( ReorderedColumns, ListToRename )
in
    RenamedColumns
